added route endpoints
GigiDev7/budget-project pull request #1
Opened 2022-03-02 09:32 UTC by GigiDev7

2022-03-02 10:11 UTC, GigiDev7 commented
Hello. I dont know exactly what kind of data i will have or what kind of collections i will have in Mongo so maybe i will have to add some more endpoints after that or remove existing.

2022-03-03 08:12 UTC, GigiDev7 commented
I saw now that i dont use authentication router anywhere and i have get  method on login , also i dont neeed logout route, i will change that

2022-03-03 08:49 UTC, GigiDev7 commented
I have bug i should have post request on login...

2022-03-05 05:20 UTC, Lokki17 requested changes
Please fix remarks

2022-03-05 05:20 UTC, Lokki17 commented on controllers/account.js
> +const getAllAccounts = (req, res) => {
It's better to split logic by layers (controllers, services, data)
Controllers are used to handle request, services to store busines logic and data-layer to store data. In your case, I think, service and data will be combined.
In general cases services shouldnt know about requests.
Just move busines logic to another file.

2022-03-05 05:20 UTC, Lokki17 commented on controllers/expanses.js
> +const getExpanses = (req, res) => {
the same remark as for account

2022-03-05 05:20 UTC, Lokki17 commented on controllers/incomes.js
> +const getIncomes = (req, res) => {
the same remark as for account

2022-03-05 09:20 UTC, GigiDev7 commented on controllers/account.js
> +const getAllAccounts = (req, res) => {
Hello, for data I will have models folder like MVC architecture(but i won't have views in this project beecause we use client side rendering).

2022-03-05 09:33 UTC, GigiDev7 commented
As i understood i should have services folder where i put logics, like database queries, algorithms and stuff, then i import them in controllers and just call it in controller. i dont have any logic right now because i dont have any database or data to return but i will add services folder after i have it, i never used it but i think i guessed what i should do

2022-03-05 09:44 UTC, GigiDev7 commented
I made services folder and made example function, is it the way it should be? or i did not get it right?

2022-03-05 09:48 UTC, GigiDev7 commented
I'll add models folder for mongoose schemas after we start working with DB

2022-03-05 13:15 UTC, Lokki17 approved these changes

2022-03-05 13:15 UTC, Lokki17 commented on controllers/account.js
> +const getAllAccounts = (req, res) => {
Ok

2022-03-05 13:18 UTC, Lokki17 commented
> I made services folder and made example function, is it the way it should be? or i did not get it right?

Yes. It's correct

2022-03-05 14:29 UTC, GigiDev7 commented
Thank you!

2022-03-05 20:12 UTC, merged